name: Destroy Terraform AWS Infrastructure

on:
  workflow_dispatch:

jobs:
  destroy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Setup Terraform
      uses: hashicorp/setup-terraform@v3

    - name: Plan Deployment Destroy
      run: terraform plan -destroy
      working-directory: ./aws/environments/dev
      env:
        TF_VAR_container_image: tommstrdev/portfolio:0.1.8
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        
    - name: Destroy Infrastructure
      run: terraform destroy -auto-approve
      working-directory: ./aws/environments/dev
      env:
        TF_VAR_container_image: tommstrdev/portfolio:0.1.8
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
